language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install autotools-dev libssl-dev xsltproc doxygen graphviz libgtk2.0-dev libqt4-dev libapr1-dev apache2-threaded-dev unixodbc-dev
script:
  - ./autogen.sh
  - ./configure && make && make check

