#!/bin/sh
# Script for regenerating all autogenerated files.

if [ -f /usr/local/share/gettext/gettext.h ]; then
cp /usr/local/share/gettext/gettext.h gettext.h
else
if [ -f /usr/share/gettext/gettext.h ]; then
cp /usr/share/gettext/gettext.h gettext.h
else
echo "You should have gettext package installed."
exit
fi
fi

if [ -f /usr/local/share/aclocal/libtool.m4 ]; then
cp /usr/local/share/aclocal/libtool.m4 ./aclocal.m4
else
if [ -f /usr/share/aclocal/libtool.m4 ]; then
cp /usr/share/aclocal/libtool.m4 ./aclocal.m4
else
echo "You should have libtool package installed."
exit
fi
fi

autopoint -f
libtoolize -c -f
aclocal -I m4
autoheader &&
automake --gnu -c -a &&
autoconf &&
autoheader

# Regenerate language files for gettext
if [ -f po/POTFILES.in ]; then
rm -f po/POTFILES.in
fi
touch po/POTFILES.in
find ./src -name '*.cpp' >>po/POTFILES.in
find ./src -name '*.h' >>po/POTFILES.in
xgettext -k_ -f po/POTFILES.in -C -F -o libdcl.pot -p po
cd po
rm -rf LINGUAS
touch LINGUAS
if [ -f *.po ]; then
for f in *.po; do
  lang=`echo $f | sed -e 's,\.po$,,'`
  msgmerge -U $lang.po libdcl.pot
  msgfmt -c -o $lang.gmo $lang.po
  echo $lang >>LINGUAS
done
fi
cd ..

# Fix permissions
find . -type d -exec chmod ugo+rwx,o-w '{}' ';'
find . -type f -exec chmod ugo+rw,ugo-x,o-w '{}' ';'
chmod ugo+x *.sh
chmod ugo+x debian/rules
chmod ugo+x configure

